parameters:
#    services.example.class: BodaClick\ServicesBundle\Example

services:
#    services.example:
#        class: %services.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
